# Generated by Django 5.0.8 on 2024-08-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Genre',
        ),
    ]
