# Generated by Django 5.0.8 on 2024-08-13 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('genres', '0002_rename_gender_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Data de Lançamento')),
                ('resume', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('actors', models.ManyToManyField(related_name='movies', to='actors.actor', verbose_name='Atores')),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movies', to='genres.genre', verbose_name='Gêneros')),
            ],
            options={
                'verbose_name': 'Filme',
                'ordering': ['title'],
            },
        ),
    ]
